apiVersion: v2
name: backend
description: backend service chart
type: application
version: 0.1.0
dependencies:
- name: webapp-base
  version: 0.1.0
  repository: "file://../../base/webapp-base"
  condition: webapp-base.enabled
  tags:
  - "webapp-base"
