apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-prd
  namespace: argocd
spec:
  destination:
    namespace: exchange-backend-prd
    server: "https://kubernetes.default.svc"
  project: exchange-backend-prd
  source:
    path: prd/backend
    repoURL: https://github.com/NeorCloud/neor-demo-apps.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Validate=false
    - Prune=true
    - SelfHeal=true
