apiVersion: v2
name: crunchy-psql-cluster
description: "An Umbrella Helm Chart for crunchy-postgres"
type: application
version: 0.1.0
dependencies:
  - name: postgrescluster
    version: 5.x.x
    repository: oci://registry.sh1.exchange.neor.space/helm-charts
    condition: postgrescluster.enabled
